{
 "title": "Satisfactory",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sessionName", "label": "Session Name", "query": { "query": "label_values(sessionName)" } }
  ]
 },
 "panels": [
  {
   "title": "Players Online",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_server_game_state_num_connected_players{}",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "satisfactory_server_game_state_num_connected_players{}",
     "legendFormat": "Players"
    }
   ]
  },
  {
   "title": "Unpaused Game Time",
   "type": "stat",
   "description": "How long the game has been running in total, i.e. had at least one player online.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_server_game_state_total_game_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tech Tier",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_server_game_state_tech_tier",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conveyors Placed (meters)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_conveyors_meters{sessionName=\"$sessionName\"}",
     "legendFormat": "Mk.{{mk}}"
    }
   ]
  },
  {
   "title": "Train velocities",
   "type": "timeseries",
   "description": "At least XX% of the trains are moving at least this speed",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "satisfactory_savegame_trains_current_speed{quantile=\"0.5\", sessionName=\"$sessionName\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "satisfactory_savegame_trains_current_speed{quantile=\"0.95\", sessionName=\"$sessionName\"}",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "AWESOME points collected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_awesome_points{sessionName=\"$sessionName\"}",
     "legendFormat": "{{sessionName}}"
    }
   ]
  },
  {
   "title": "Pipelines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_pipes_meters{sessionName=\"$sessionName\"}",
     "legendFormat": "Pipeline Mk{{mk}}"
    }
   ]
  },
  {
   "title": "Foundations & Walls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_buildings_lightweight_total{building=~\"Foundation|Wall\",sessionName=\"$sessionName\"}",
     "legendFormat": "{{building}}s"
    }
   ]
  },
  {
   "title": "Resource production/consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "((satisfactory_savegame_resources_production_per_second{sessionName=\"$sessionName\"} - satisfactory_savegame_resources_consumption_per_second{sessionName=\"$sessionName\"}) or satisfactory_savegame_resources_production_per_second{sessionName=\"$sessionName\"} or (satisfactory_savegame_resources_consumption_per_second{sessionName=\"$sessionName\"} * -1)) * 60",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Power production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "satisfactory_savegame_power_production_megawatts{sessionName=\"$sessionName\"}",
     "legendFormat": "{{building}}"
    }
   ]
  },
  {
   "title": "Deficits",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "((satisfactory_savegame_resources_production_per_second{sessionName=\"$sessionName\"} - satisfactory_savegame_resources_consumption_per_second{sessionName=\"$sessionName\"}) or satisfactory_savegame_resources_production_per_second{sessionName=\"$sessionName\"} or (satisfactory_savegame_resources_consumption_per_second{sessionName=\"$sessionName\"} * -1)) * 60",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Buildings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "satisfactory_savegame_buildings_total{sessionName=\"$sessionName\",\"building\"!~\".*(Conveyor|Pipeline|Power|Outlet|Hypert|Railway|Signal).*|.*Wall|Ladder\"}",
     "legendFormat": "{{building}}"
    }
   ]
  },
  {
   "title": "Power lines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_power_powerlines_meters{sessionName=\"$sessionName\"}",
     "legendFormat": "Power lines"
    }
   ]
  },
  {
   "title": "Railway",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satisfactory_savegame_trains_tracks_meters{sessionName=\"$sessionName\"}",
     "legendFormat": "Train tracks"
    }
   ]
  }
 ]
}